### ISSUE TITLE
integer Number no longer works

### ISSUE THREAD

**Issue by rukai** [serde-rs/json#320]
I've been using this in a project of mine for a while now but it no longer works. The code path isnt taken often so I dont really know when it broke, was probably serde 1.0 though.

Example:
```
extern crate serde_json;

use serde_json::{Value, Number};

pub fn main() {
    let value = 4;
    let number = Value::Number(Number::from_f64(value as f64).unwrap());
    let des_value: u64 = serde_json::from_value(number).unwrap();
    assert_eq!(value, des_value);
}
```

output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: floating point `4`, expected u64"), line: 0, column: 0 }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: foo::main
             at ./main.rs:8
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by dtolnay** [comment]
Yep, this implicit conversion from float to integer was removed in 1.0 along with some other implicit conversions that were doing more harm than good.

This conversion was broken anyway, so it's good that this uncovered a problem in your code. For instance in serde_json 0.9:

```rust
#[macro_use]
extern crate serde_json;

pub fn main() {
    let number = json!(10000.0);
    let des_value: u8 = serde_json::from_value(number).unwrap();
    assert_eq!(des_value, 16); // what?
}
```

It turned out there wasn't a way to define float to int conversion in a way that most people would be happy with, so as of 1.0 we leave it to users to do whatever conversion is right for their situation.

**Comment by rukai** [comment]
Oh. I see what the issue is now. 
Looking at the docs, https://docs.serde.rs/serde_json/struct.Number.html
Its very easy to come to the conclusion that you can only construct Number from an f64.
The From trait methods are hidden at the bottom.

If other people run into this a lot you may want to duplicate the From traits as normal methods.
However not doing so is also completely reasonable.

Sorry for the false report and thanks for the fantastic library.
