### ISSUE TITLE
`trailing characters` error

### ISSUE THREAD

**Issue by c-o-l-o-r** [serde-rs/json#549]
When deserialize the following into the `serde_json::Value`

```json
"123:u32"
```

I receive the error that there are `trailing characters`, but AFAIK this is valid JSON.

**Comment by dtolnay** [comment]
I was not able to reproduce this.

```rust
fn main() {
    let j = std::fs::read_to_string("c-o-l-o-r.json").unwrap();
    let v = serde_json::from_str::<serde_json::Value>(&j).unwrap();
    println!("{:?}", v);
}
```

```console
$ cat c-o-l-o-r.json 
"123:u32"

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/testing`
String("123:u32")
```

**Comment by c-o-l-o-r** [comment]
Sorry, I should have been more specific:

```rust
fn main() {
    let json = "123:u32";
    let v: serde_json::Value = serde_json::from_str(json).unwrap();
    println!("{:?}", v);
 }
```

```console
$ cargo run
   Compiling serde-json-issue v0.1.0 (/Users/matt/Development/serde-json-not-preserving-order)
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
     Running `target/debug/serde-json-issue`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 4)', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
  10: serde_json_issue::main
             at src/main.rs:5
  11: std::rt::lang_start::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  16: serde_json_issue::main
```

I've tried on v1.34.0 and nightly, but no luck.

**Comment by dtolnay** [comment]
This is correct behavior. Your input is not valid JSON.

Here is a JSON validator: https://codebeautify.org/jsonvalidator/cb94700e

**Comment by c-o-l-o-r** [comment]
Ah, I see now. I forgot the inner quotes. Apologies!
