### ISSUE TITLE
Deserializing string with newlines into HashMap<&str, &str> fails but HashMap<String, String> works

### ISSUE THREAD

**Issue by davidpdrsn** [serde-rs/json#570]
I'm not sure what is going on here, but it seems that deserializing into `HashMap<&str, &str>` fails if the value contains a newline, whereas `HashMap<String, String>` works just fine.

This fails:

```rust
use std::collections::HashMap;

fn main() {
    let json = r#" { "foo": "bar\nbaz" } "#;

    let map: HashMap<&'static str, &'static str> =
        serde_json::from_str(&json).expect("deserialize");

    dbg!(map);
}
```

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/i18n-test`
thread 'main' panicked at 'deserialize: Error("invalid type: string \"bar\\nbaz\", expected a borrowed string", line: 1, column: 20)', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:827
  12: i18n_test::main
             at src/main.rs:8
  13: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  21: i18n_test::main
```

This works:

```rust
use std::collections::HashMap;

fn main() {
    let json = r#" { "foo": "bar\nbaz" } "#;

    let map: HashMap<String, String> = serde_json::from_str(&json).expect("deserialize");

    dbg!(map);
}
```

```
$ cargo run
   Compiling i18n-test v0.1.0 (/Users/davidpdrsn/Desktop/i18n-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/i18n-test`
[src/main.rs:8] map = {
    "foo": "bar\nbaz",
}
```

Any idea what could be going on here?

**Comment by dtolnay** [comment]
After deserialization of that JSON, the value associated with the key "foo" would need to contain a newline character (U+000A, or '0x0a'). Your input string does not contain a newline character anywhere. Thus there isn't any substring of the input that can be borrowed as &str in the output that would have the correct value.

**Comment by davidpdrsn** [comment]
Hm alright. Not quite sure I understand, but I take your word for it 😊

Is there anyway to deserialise that JSON without creating new `String`s?

**Comment by dtolnay** [comment]
If what you want is for the escape sequence to be kept as two characters `\` `n` in the output, you could use `HashMap<&str, &RawValue>`. https://docs.rs/serde_json/1.0/serde_json/value/struct.RawValue.html

**Comment by davidpdrsn** [comment]
I'll give that a shot. Thanks!
